### ISSUE TITLE
Get rid of romanji

### ISSUE THREAD

**Issue by tristaaan** [tristaaan/SayThisNumber#14]
No transliterations, sub in correct characters.

**Comment by tristaaan** [comment]
241 should read out how it is fully spoken using the/(a?) Japanese writing system. It's a writing system I'm not familiar with so if you wrote a parser I'd certainly merge it.

**Comment by wozzo** [comment]
They are both correct. Japanese has three writing systems. Hiragana, Katakana and Kanji. I guess a separate parser would be required for each.

**Comment by tristaaan** [comment]
The approach for Chinese was to write one for each language. I'd accept the same for Japanese.
