### ISSUE TITLE
Numbers are innaccurate in human readable language around 10 quadrillion mark

### ISSUE THREAD

**Issue by jaredpetersen** [tristaaan/SayThisNumber#22]
Numbers become innaccurate in human readable language (confirmed in English), around the ten quadrillion mark:

Correct:
http://www.saythisnumber.in/english/1000000000000099
Expected result: One quadrillion and ninety nine
Actual result: One quadrillion and ninety nine

Incorrect:
http://www.saythisnumber.in/english/10000000000000099
Expected result: ten quadrillion and ninety nine
Actual result: ten quadrillion and one hundred

**Comment by tristaaan** [comment]
Similar to #12, though more specific and further investigation shows it's looks more critical than originally thought though. Playing around locally and in a js console here's a problem with a few large numbers in that range.
I think I'm going to limit numbers to ± one quadrillion.
