### ISSUE TITLE
'Failed to decode' - message after putting a '%' in the title bar

### ISSUE THREAD

**Issue by Krettis** [tristaaan/SayThisNumber#24]
Calling http://www.saythisnumber.in/english/4 everything goes well.

http://www.saythisnumber.in/english/4[a-z] will always get a header that it cannot GET this output.

But http://www.saythisnumber.in/english/4% will get the following error:

>Error: Failed to decode param '4%' at Route.match (/app/node_modules/express/lib/router/route.js:65:17) at Router.matchRequest (/app/node_modules/express/lib/router/index.js:244:17) at pass (/app/node_modules/express/lib/router/index.js:104:30) at Router._dispatch (/app/node_modules/express/lib/router/index.js:173:5) at Object.router (/app/node_modules/express/lib/router/index.js:33:10) at next (/app/node_modules/express/node_modules/connect/lib/proto.js:194:15) at Object.expressInit [as handle] (/app/node_modules/express/lib/middleware.js:30:5) at next (/app/node_modules/express/node_modules/connect/lib/proto.js:194:15) at Object.query [as handle] (/app/node_modules/express/node_modules/connect/lib/middleware/query.js:45:5) at next (/app/node_modules/express/node_modules/connect/lib/proto.js:194:15)

**Comment by tristaaan** [comment]
Thanks for specifically pointing these out. Fixed.

**Comment by Krettis** [comment]
nice :+1:
