### ISSUE TITLE
Different outputs

### ISSUE THREAD

**Issue by Krettis** [tristaaan/SayThisNumber#25]
Would be nice to not only have a normal page output but also in json, csv, text.

Example:

`2-5`
#### text/plain

two(newline)
three(newline)
four(newline)
five(newline)
#### csv

two,three,four,five;
#### json

{[
"2" : "two",
"3" : "three",
"4" : "four",
"5" : "five",
]}

**Comment by tristaaan** [comment]
I like this idea. Formatted requests would be something like `[language]/[number]/[format]`. Maybe this could also replace the current POST routes too.

**Comment by Krettis** [comment]
I've made gist out what [stormpath](https://www.youtube.com/watch?v=hdSrT4yjS1g) seems to think what is best for a rest

https://gist.github.com/Krettis/79f5233cea5f76f14643


I think 
     {LANG}/{NUMBER}.{FORMAT} 

would work better.
`/format` would indicate that it is another resource, and that is not the case.

**Comment by tristaaan** [comment]
That makes more sense, thanks for the links too.

Think CSV should be more
```
2-5
->
2,two
3,three
4,four
5,five
```
to keep in a more tabular format?

**Comment by Krettis** [comment]
Yeah, you are right :)

**Comment by tristaaan** [comment]
Closing this issue as it's moving away from a server model (STNaaS: saythisnumber as a service) and to a library package (pull #37)
